/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 5.12.6
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QTextEdit>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *Title;
    QLabel *SaveFile1;
    QPushButton *LoadSaveFile1;
    QPushButton *NewSaveFile1;
    QPushButton *DeleteSaveFile1;
    QLabel *SaveFile2;
    QPushButton *LoadSaveFile2;
    QPushButton *NewSaveFile2;
    QPushButton *DeleteSaveFile2;
    QLabel *SaveFile3;
    QPushButton *LoadSaveFile3;
    QPushButton *NewSaveFile3;
    QPushButton *DeleteSaveFile3;
    QTextEdit *FileName;
    QLabel *Name;
    QLabel *Player;
    QPushButton *Human;
    QPushButton *ArtificialIntelligence;
    QLabel *Difficulty;
    QPushButton *Easy;
    QPushButton *Impossible;
    QLabel *Computer;
    QPushButton *Red;
    QPushButton *Yellow;
    QPushButton *Back;
    QPushButton *CreateFile;
    QLabel *PlayerOutput;
    QLabel *DifficultyOutput;
    QLabel *ComputerOutput;
    QLabel *Board;
    QLabel *Red00;
    QLabel *Yellow00;
    QLabel *Red10;
    QLabel *Yellow10;
    QLabel *Red20;
    QLabel *Yellow20;
    QLabel *Red30;
    QLabel *Yellow30;
    QLabel *Red40;
    QLabel *Yellow40;
    QLabel *Red50;
    QLabel *Yellow50;
    QLabel *Red01;
    QLabel *Yellow01;
    QLabel *Red11;
    QLabel *Yellow11;
    QLabel *Red21;
    QLabel *Yellow21;
    QLabel *Red31;
    QLabel *Yellow31;
    QLabel *Red41;
    QLabel *Yellow41;
    QLabel *Red51;
    QLabel *Yellow51;
    QLabel *Red02;
    QLabel *Yellow02;
    QLabel *Red12;
    QLabel *Yellow12;
    QLabel *Red22;
    QLabel *Yellow22;
    QLabel *Red32;
    QLabel *Yellow32;
    QLabel *Red42;
    QLabel *Yellow42;
    QLabel *Red52;
    QLabel *Yellow52;
    QLabel *Red03;
    QLabel *Yellow03;
    QLabel *Red13;
    QLabel *Yellow13;
    QLabel *Red23;
    QLabel *Yellow23;
    QLabel *Red33;
    QLabel *Yellow33;
    QLabel *Red43;
    QLabel *Yellow43;
    QLabel *Red53;
    QLabel *Yellow53;
    QLabel *Red04;
    QLabel *Yellow04;
    QLabel *Red14;
    QLabel *Yellow14;
    QLabel *Red24;
    QLabel *Yellow24;
    QLabel *Red34;
    QLabel *Yellow34;
    QLabel *Red44;
    QLabel *Yellow44;
    QLabel *Red54;
    QLabel *Yellow54;
    QLabel *Red05;
    QLabel *Yellow05;
    QLabel *Red15;
    QLabel *Yellow15;
    QLabel *Red25;
    QLabel *Yellow25;
    QLabel *Red35;
    QLabel *Yellow35;
    QLabel *Red45;
    QLabel *Yellow45;
    QLabel *Red55;
    QLabel *Yellow55;
    QLabel *Red06;
    QLabel *Yellow06;
    QLabel *Red16;
    QLabel *Yellow16;
    QLabel *Red26;
    QLabel *Yellow26;
    QLabel *Red36;
    QLabel *Yellow36;
    QLabel *Red46;
    QLabel *Yellow46;
    QLabel *Red56;
    QLabel *Yellow56;
    QPushButton *Drop0;
    QPushButton *Drop1;
    QPushButton *Drop2;
    QPushButton *Drop3;
    QPushButton *Drop4;
    QPushButton *Drop5;
    QPushButton *Drop6;
    QLabel *Loading;
    QPushButton *PlayAgain;
    QPushButton *Exit;
    QLabel *RedWins;
    QLabel *YellowWins;
    QLabel *ItsATie;
    QLabel *RedgoesFirst;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName(QString::fromUtf8("MainWindow"));
        MainWindow->resize(1971, 1248);
        MainWindow->setMaximumSize(QSize(16777215, 16777215));
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName(QString::fromUtf8("centralwidget"));
        Title = new QLabel(centralwidget);
        Title->setObjectName(QString::fromUtf8("Title"));
        Title->setGeometry(QRect(750, 30, 581, 91));
        QFont font;
        font.setPointSize(20);
        font.setBold(true);
        font.setWeight(75);
        Title->setFont(font);
        SaveFile1 = new QLabel(centralwidget);
        SaveFile1->setObjectName(QString::fromUtf8("SaveFile1"));
        SaveFile1->setGeometry(QRect(0, 150, 1971, 241));
        QFont font1;
        font1.setPointSize(20);
        SaveFile1->setFont(font1);
        LoadSaveFile1 = new QPushButton(centralwidget);
        LoadSaveFile1->setObjectName(QString::fromUtf8("LoadSaveFile1"));
        LoadSaveFile1->setGeometry(QRect(0, 390, 691, 141));
        QFont font2;
        font2.setPointSize(30);
        font2.setBold(true);
        font2.setWeight(75);
        LoadSaveFile1->setFont(font2);
        NewSaveFile1 = new QPushButton(centralwidget);
        NewSaveFile1->setObjectName(QString::fromUtf8("NewSaveFile1"));
        NewSaveFile1->setGeometry(QRect(690, 390, 631, 141));
        NewSaveFile1->setFont(font2);
        DeleteSaveFile1 = new QPushButton(centralwidget);
        DeleteSaveFile1->setObjectName(QString::fromUtf8("DeleteSaveFile1"));
        DeleteSaveFile1->setGeometry(QRect(1320, 390, 651, 141));
        DeleteSaveFile1->setFont(font2);
        SaveFile2 = new QLabel(centralwidget);
        SaveFile2->setObjectName(QString::fromUtf8("SaveFile2"));
        SaveFile2->setGeometry(QRect(0, 530, 1971, 251));
        SaveFile2->setFont(font1);
        LoadSaveFile2 = new QPushButton(centralwidget);
        LoadSaveFile2->setObjectName(QString::fromUtf8("LoadSaveFile2"));
        LoadSaveFile2->setGeometry(QRect(0, 750, 691, 151));
        LoadSaveFile2->setFont(font2);
        NewSaveFile2 = new QPushButton(centralwidget);
        NewSaveFile2->setObjectName(QString::fromUtf8("NewSaveFile2"));
        NewSaveFile2->setGeometry(QRect(690, 750, 631, 151));
        NewSaveFile2->setFont(font2);
        DeleteSaveFile2 = new QPushButton(centralwidget);
        DeleteSaveFile2->setObjectName(QString::fromUtf8("DeleteSaveFile2"));
        DeleteSaveFile2->setGeometry(QRect(1320, 750, 651, 151));
        DeleteSaveFile2->setFont(font2);
        SaveFile3 = new QLabel(centralwidget);
        SaveFile3->setObjectName(QString::fromUtf8("SaveFile3"));
        SaveFile3->setGeometry(QRect(0, 910, 1971, 161));
        SaveFile3->setFont(font1);
        LoadSaveFile3 = new QPushButton(centralwidget);
        LoadSaveFile3->setObjectName(QString::fromUtf8("LoadSaveFile3"));
        LoadSaveFile3->setGeometry(QRect(0, 1060, 691, 131));
        LoadSaveFile3->setFont(font2);
        NewSaveFile3 = new QPushButton(centralwidget);
        NewSaveFile3->setObjectName(QString::fromUtf8("NewSaveFile3"));
        NewSaveFile3->setGeometry(QRect(690, 1060, 631, 131));
        NewSaveFile3->setFont(font2);
        DeleteSaveFile3 = new QPushButton(centralwidget);
        DeleteSaveFile3->setObjectName(QString::fromUtf8("DeleteSaveFile3"));
        DeleteSaveFile3->setGeometry(QRect(1320, 1060, 651, 131));
        DeleteSaveFile3->setFont(font2);
        FileName = new QTextEdit(centralwidget);
        FileName->setObjectName(QString::fromUtf8("FileName"));
        FileName->setGeometry(QRect(90, 660, 501, 321));
        FileName->setFont(font1);
        Name = new QLabel(centralwidget);
        Name->setObjectName(QString::fromUtf8("Name"));
        Name->setGeometry(QRect(90, 350, 661, 321));
        QFont font3;
        font3.setPointSize(30);
        Name->setFont(font3);
        Player = new QLabel(centralwidget);
        Player->setObjectName(QString::fromUtf8("Player"));
        Player->setGeometry(QRect(610, 370, 281, 91));
        Player->setFont(font3);
        Human = new QPushButton(centralwidget);
        Human->setObjectName(QString::fromUtf8("Human"));
        Human->setGeometry(QRect(610, 460, 481, 171));
        Human->setFont(font1);
        ArtificialIntelligence = new QPushButton(centralwidget);
        ArtificialIntelligence->setObjectName(QString::fromUtf8("ArtificialIntelligence"));
        ArtificialIntelligence->setGeometry(QRect(610, 650, 481, 171));
        ArtificialIntelligence->setFont(font1);
        Difficulty = new QLabel(centralwidget);
        Difficulty->setObjectName(QString::fromUtf8("Difficulty"));
        Difficulty->setGeometry(QRect(1110, 370, 381, 91));
        Difficulty->setFont(font3);
        Easy = new QPushButton(centralwidget);
        Easy->setObjectName(QString::fromUtf8("Easy"));
        Easy->setGeometry(QRect(1110, 460, 371, 171));
        Easy->setFont(font1);
        Impossible = new QPushButton(centralwidget);
        Impossible->setObjectName(QString::fromUtf8("Impossible"));
        Impossible->setGeometry(QRect(1110, 650, 371, 171));
        Impossible->setFont(font1);
        Computer = new QLabel(centralwidget);
        Computer->setObjectName(QString::fromUtf8("Computer"));
        Computer->setGeometry(QRect(1510, 370, 401, 91));
        Computer->setFont(font3);
        Red = new QPushButton(centralwidget);
        Red->setObjectName(QString::fromUtf8("Red"));
        Red->setGeometry(QRect(1510, 460, 441, 171));
        Red->setFont(font1);
        Yellow = new QPushButton(centralwidget);
        Yellow->setObjectName(QString::fromUtf8("Yellow"));
        Yellow->setGeometry(QRect(1510, 650, 441, 171));
        Yellow->setFont(font1);
        Back = new QPushButton(centralwidget);
        Back->setObjectName(QString::fromUtf8("Back"));
        Back->setGeometry(QRect(20, 1000, 471, 201));
        Back->setFont(font3);
        CreateFile = new QPushButton(centralwidget);
        CreateFile->setObjectName(QString::fromUtf8("CreateFile"));
        CreateFile->setGeometry(QRect(610, 1000, 661, 201));
        CreateFile->setFont(font1);
        PlayerOutput = new QLabel(centralwidget);
        PlayerOutput->setObjectName(QString::fromUtf8("PlayerOutput"));
        PlayerOutput->setGeometry(QRect(610, 840, 481, 141));
        PlayerOutput->setFont(font1);
        DifficultyOutput = new QLabel(centralwidget);
        DifficultyOutput->setObjectName(QString::fromUtf8("DifficultyOutput"));
        DifficultyOutput->setGeometry(QRect(1110, 840, 371, 141));
        DifficultyOutput->setFont(font1);
        ComputerOutput = new QLabel(centralwidget);
        ComputerOutput->setObjectName(QString::fromUtf8("ComputerOutput"));
        ComputerOutput->setGeometry(QRect(1510, 840, 441, 141));
        ComputerOutput->setFont(font1);
        Board = new QLabel(centralwidget);
        Board->setObjectName(QString::fromUtf8("Board"));
        Board->setGeometry(QRect(410, 130, 1971, 1221));
        Board->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Connect 4 Board.jpg")));
        Red00 = new QLabel(centralwidget);
        Red00->setObjectName(QString::fromUtf8("Red00"));
        Red00->setGeometry(QRect(420, 290, 146, 146));
        Red00->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow00 = new QLabel(centralwidget);
        Yellow00->setObjectName(QString::fromUtf8("Yellow00"));
        Yellow00->setGeometry(QRect(420, 290, 146, 146));
        Yellow00->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red10 = new QLabel(centralwidget);
        Red10->setObjectName(QString::fromUtf8("Red10"));
        Red10->setGeometry(QRect(420, 440, 146, 146));
        Red10->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow10 = new QLabel(centralwidget);
        Yellow10->setObjectName(QString::fromUtf8("Yellow10"));
        Yellow10->setGeometry(QRect(420, 440, 146, 146));
        Yellow10->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red20 = new QLabel(centralwidget);
        Red20->setObjectName(QString::fromUtf8("Red20"));
        Red20->setGeometry(QRect(420, 590, 146, 146));
        Red20->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow20 = new QLabel(centralwidget);
        Yellow20->setObjectName(QString::fromUtf8("Yellow20"));
        Yellow20->setGeometry(QRect(420, 590, 146, 146));
        Yellow20->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red30 = new QLabel(centralwidget);
        Red30->setObjectName(QString::fromUtf8("Red30"));
        Red30->setGeometry(QRect(420, 750, 146, 146));
        Red30->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow30 = new QLabel(centralwidget);
        Yellow30->setObjectName(QString::fromUtf8("Yellow30"));
        Yellow30->setGeometry(QRect(420, 750, 146, 146));
        Yellow30->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red40 = new QLabel(centralwidget);
        Red40->setObjectName(QString::fromUtf8("Red40"));
        Red40->setGeometry(QRect(420, 900, 146, 146));
        Red40->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow40 = new QLabel(centralwidget);
        Yellow40->setObjectName(QString::fromUtf8("Yellow40"));
        Yellow40->setGeometry(QRect(420, 900, 146, 146));
        Yellow40->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red50 = new QLabel(centralwidget);
        Red50->setObjectName(QString::fromUtf8("Red50"));
        Red50->setGeometry(QRect(420, 1050, 146, 146));
        Red50->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow50 = new QLabel(centralwidget);
        Yellow50->setObjectName(QString::fromUtf8("Yellow50"));
        Yellow50->setGeometry(QRect(420, 1050, 146, 146));
        Yellow50->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red01 = new QLabel(centralwidget);
        Red01->setObjectName(QString::fromUtf8("Red01"));
        Red01->setGeometry(QRect(580, 290, 146, 146));
        Red01->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow01 = new QLabel(centralwidget);
        Yellow01->setObjectName(QString::fromUtf8("Yellow01"));
        Yellow01->setGeometry(QRect(580, 290, 146, 146));
        Yellow01->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red11 = new QLabel(centralwidget);
        Red11->setObjectName(QString::fromUtf8("Red11"));
        Red11->setGeometry(QRect(580, 440, 146, 146));
        Red11->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow11 = new QLabel(centralwidget);
        Yellow11->setObjectName(QString::fromUtf8("Yellow11"));
        Yellow11->setGeometry(QRect(580, 440, 146, 146));
        Yellow11->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red21 = new QLabel(centralwidget);
        Red21->setObjectName(QString::fromUtf8("Red21"));
        Red21->setGeometry(QRect(580, 590, 146, 146));
        Red21->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow21 = new QLabel(centralwidget);
        Yellow21->setObjectName(QString::fromUtf8("Yellow21"));
        Yellow21->setGeometry(QRect(580, 590, 146, 146));
        Yellow21->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red31 = new QLabel(centralwidget);
        Red31->setObjectName(QString::fromUtf8("Red31"));
        Red31->setGeometry(QRect(580, 750, 146, 146));
        Red31->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow31 = new QLabel(centralwidget);
        Yellow31->setObjectName(QString::fromUtf8("Yellow31"));
        Yellow31->setGeometry(QRect(580, 750, 146, 146));
        Yellow31->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red41 = new QLabel(centralwidget);
        Red41->setObjectName(QString::fromUtf8("Red41"));
        Red41->setGeometry(QRect(580, 900, 146, 146));
        Red41->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow41 = new QLabel(centralwidget);
        Yellow41->setObjectName(QString::fromUtf8("Yellow41"));
        Yellow41->setGeometry(QRect(580, 900, 146, 146));
        Yellow41->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red51 = new QLabel(centralwidget);
        Red51->setObjectName(QString::fromUtf8("Red51"));
        Red51->setGeometry(QRect(580, 1050, 146, 146));
        Red51->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow51 = new QLabel(centralwidget);
        Yellow51->setObjectName(QString::fromUtf8("Yellow51"));
        Yellow51->setGeometry(QRect(580, 1050, 146, 146));
        Yellow51->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red02 = new QLabel(centralwidget);
        Red02->setObjectName(QString::fromUtf8("Red02"));
        Red02->setGeometry(QRect(740, 290, 146, 146));
        Red02->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow02 = new QLabel(centralwidget);
        Yellow02->setObjectName(QString::fromUtf8("Yellow02"));
        Yellow02->setGeometry(QRect(740, 290, 146, 146));
        Yellow02->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red12 = new QLabel(centralwidget);
        Red12->setObjectName(QString::fromUtf8("Red12"));
        Red12->setGeometry(QRect(740, 440, 146, 146));
        Red12->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow12 = new QLabel(centralwidget);
        Yellow12->setObjectName(QString::fromUtf8("Yellow12"));
        Yellow12->setGeometry(QRect(740, 440, 146, 146));
        Yellow12->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red22 = new QLabel(centralwidget);
        Red22->setObjectName(QString::fromUtf8("Red22"));
        Red22->setGeometry(QRect(740, 590, 146, 146));
        Red22->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow22 = new QLabel(centralwidget);
        Yellow22->setObjectName(QString::fromUtf8("Yellow22"));
        Yellow22->setGeometry(QRect(740, 590, 146, 146));
        Yellow22->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red32 = new QLabel(centralwidget);
        Red32->setObjectName(QString::fromUtf8("Red32"));
        Red32->setGeometry(QRect(740, 750, 146, 146));
        Red32->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow32 = new QLabel(centralwidget);
        Yellow32->setObjectName(QString::fromUtf8("Yellow32"));
        Yellow32->setGeometry(QRect(740, 750, 146, 146));
        Yellow32->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red42 = new QLabel(centralwidget);
        Red42->setObjectName(QString::fromUtf8("Red42"));
        Red42->setGeometry(QRect(740, 900, 146, 146));
        Red42->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow42 = new QLabel(centralwidget);
        Yellow42->setObjectName(QString::fromUtf8("Yellow42"));
        Yellow42->setGeometry(QRect(740, 900, 146, 146));
        Yellow42->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red52 = new QLabel(centralwidget);
        Red52->setObjectName(QString::fromUtf8("Red52"));
        Red52->setGeometry(QRect(740, 1050, 146, 146));
        Red52->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow52 = new QLabel(centralwidget);
        Yellow52->setObjectName(QString::fromUtf8("Yellow52"));
        Yellow52->setGeometry(QRect(740, 1050, 146, 146));
        Yellow52->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red03 = new QLabel(centralwidget);
        Red03->setObjectName(QString::fromUtf8("Red03"));
        Red03->setGeometry(QRect(910, 290, 146, 146));
        Red03->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow03 = new QLabel(centralwidget);
        Yellow03->setObjectName(QString::fromUtf8("Yellow03"));
        Yellow03->setGeometry(QRect(910, 290, 146, 146));
        Yellow03->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red13 = new QLabel(centralwidget);
        Red13->setObjectName(QString::fromUtf8("Red13"));
        Red13->setGeometry(QRect(910, 440, 146, 146));
        Red13->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow13 = new QLabel(centralwidget);
        Yellow13->setObjectName(QString::fromUtf8("Yellow13"));
        Yellow13->setGeometry(QRect(910, 440, 146, 146));
        Yellow13->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red23 = new QLabel(centralwidget);
        Red23->setObjectName(QString::fromUtf8("Red23"));
        Red23->setGeometry(QRect(910, 590, 146, 146));
        Red23->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow23 = new QLabel(centralwidget);
        Yellow23->setObjectName(QString::fromUtf8("Yellow23"));
        Yellow23->setGeometry(QRect(910, 590, 146, 146));
        Yellow23->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red33 = new QLabel(centralwidget);
        Red33->setObjectName(QString::fromUtf8("Red33"));
        Red33->setGeometry(QRect(910, 750, 146, 146));
        Red33->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow33 = new QLabel(centralwidget);
        Yellow33->setObjectName(QString::fromUtf8("Yellow33"));
        Yellow33->setGeometry(QRect(910, 750, 146, 146));
        Yellow33->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red43 = new QLabel(centralwidget);
        Red43->setObjectName(QString::fromUtf8("Red43"));
        Red43->setGeometry(QRect(910, 900, 146, 146));
        Red43->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow43 = new QLabel(centralwidget);
        Yellow43->setObjectName(QString::fromUtf8("Yellow43"));
        Yellow43->setGeometry(QRect(910, 900, 146, 146));
        Yellow43->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red53 = new QLabel(centralwidget);
        Red53->setObjectName(QString::fromUtf8("Red53"));
        Red53->setGeometry(QRect(910, 1050, 146, 146));
        Red53->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow53 = new QLabel(centralwidget);
        Yellow53->setObjectName(QString::fromUtf8("Yellow53"));
        Yellow53->setGeometry(QRect(910, 1050, 146, 146));
        Yellow53->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red04 = new QLabel(centralwidget);
        Red04->setObjectName(QString::fromUtf8("Red04"));
        Red04->setGeometry(QRect(1070, 290, 146, 146));
        Red04->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow04 = new QLabel(centralwidget);
        Yellow04->setObjectName(QString::fromUtf8("Yellow04"));
        Yellow04->setGeometry(QRect(1070, 290, 146, 146));
        Yellow04->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red14 = new QLabel(centralwidget);
        Red14->setObjectName(QString::fromUtf8("Red14"));
        Red14->setGeometry(QRect(1070, 440, 146, 146));
        Red14->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow14 = new QLabel(centralwidget);
        Yellow14->setObjectName(QString::fromUtf8("Yellow14"));
        Yellow14->setGeometry(QRect(1070, 440, 146, 146));
        Yellow14->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red24 = new QLabel(centralwidget);
        Red24->setObjectName(QString::fromUtf8("Red24"));
        Red24->setGeometry(QRect(1070, 590, 146, 146));
        Red24->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow24 = new QLabel(centralwidget);
        Yellow24->setObjectName(QString::fromUtf8("Yellow24"));
        Yellow24->setGeometry(QRect(1070, 590, 146, 146));
        Yellow24->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red34 = new QLabel(centralwidget);
        Red34->setObjectName(QString::fromUtf8("Red34"));
        Red34->setGeometry(QRect(1070, 750, 146, 146));
        Red34->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow34 = new QLabel(centralwidget);
        Yellow34->setObjectName(QString::fromUtf8("Yellow34"));
        Yellow34->setGeometry(QRect(1070, 750, 146, 146));
        Yellow34->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red44 = new QLabel(centralwidget);
        Red44->setObjectName(QString::fromUtf8("Red44"));
        Red44->setGeometry(QRect(1070, 900, 146, 146));
        Red44->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow44 = new QLabel(centralwidget);
        Yellow44->setObjectName(QString::fromUtf8("Yellow44"));
        Yellow44->setGeometry(QRect(1070, 900, 146, 146));
        Yellow44->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red54 = new QLabel(centralwidget);
        Red54->setObjectName(QString::fromUtf8("Red54"));
        Red54->setGeometry(QRect(1070, 1050, 146, 146));
        Red54->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow54 = new QLabel(centralwidget);
        Yellow54->setObjectName(QString::fromUtf8("Yellow54"));
        Yellow54->setGeometry(QRect(1070, 1050, 146, 146));
        Yellow54->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red05 = new QLabel(centralwidget);
        Red05->setObjectName(QString::fromUtf8("Red05"));
        Red05->setGeometry(QRect(1230, 290, 146, 146));
        Red05->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow05 = new QLabel(centralwidget);
        Yellow05->setObjectName(QString::fromUtf8("Yellow05"));
        Yellow05->setGeometry(QRect(1230, 290, 146, 146));
        Yellow05->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red15 = new QLabel(centralwidget);
        Red15->setObjectName(QString::fromUtf8("Red15"));
        Red15->setGeometry(QRect(1230, 440, 146, 146));
        Red15->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow15 = new QLabel(centralwidget);
        Yellow15->setObjectName(QString::fromUtf8("Yellow15"));
        Yellow15->setGeometry(QRect(1230, 440, 146, 146));
        Yellow15->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red25 = new QLabel(centralwidget);
        Red25->setObjectName(QString::fromUtf8("Red25"));
        Red25->setGeometry(QRect(1230, 590, 146, 146));
        Red25->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow25 = new QLabel(centralwidget);
        Yellow25->setObjectName(QString::fromUtf8("Yellow25"));
        Yellow25->setGeometry(QRect(1230, 590, 146, 146));
        Yellow25->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red35 = new QLabel(centralwidget);
        Red35->setObjectName(QString::fromUtf8("Red35"));
        Red35->setGeometry(QRect(1230, 750, 146, 146));
        Red35->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow35 = new QLabel(centralwidget);
        Yellow35->setObjectName(QString::fromUtf8("Yellow35"));
        Yellow35->setGeometry(QRect(1230, 750, 146, 146));
        Yellow35->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red45 = new QLabel(centralwidget);
        Red45->setObjectName(QString::fromUtf8("Red45"));
        Red45->setGeometry(QRect(1230, 900, 146, 146));
        Red45->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow45 = new QLabel(centralwidget);
        Yellow45->setObjectName(QString::fromUtf8("Yellow45"));
        Yellow45->setGeometry(QRect(1230, 900, 146, 146));
        Yellow45->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red55 = new QLabel(centralwidget);
        Red55->setObjectName(QString::fromUtf8("Red55"));
        Red55->setGeometry(QRect(1230, 1050, 146, 146));
        Red55->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow55 = new QLabel(centralwidget);
        Yellow55->setObjectName(QString::fromUtf8("Yellow55"));
        Yellow55->setGeometry(QRect(1230, 1050, 146, 146));
        Yellow55->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red06 = new QLabel(centralwidget);
        Red06->setObjectName(QString::fromUtf8("Red06"));
        Red06->setGeometry(QRect(1400, 290, 146, 146));
        Red06->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow06 = new QLabel(centralwidget);
        Yellow06->setObjectName(QString::fromUtf8("Yellow06"));
        Yellow06->setGeometry(QRect(1400, 290, 146, 146));
        Yellow06->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red16 = new QLabel(centralwidget);
        Red16->setObjectName(QString::fromUtf8("Red16"));
        Red16->setGeometry(QRect(1400, 440, 146, 146));
        Red16->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow16 = new QLabel(centralwidget);
        Yellow16->setObjectName(QString::fromUtf8("Yellow16"));
        Yellow16->setGeometry(QRect(1400, 440, 146, 146));
        Yellow16->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red26 = new QLabel(centralwidget);
        Red26->setObjectName(QString::fromUtf8("Red26"));
        Red26->setGeometry(QRect(1400, 590, 146, 146));
        Red26->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow26 = new QLabel(centralwidget);
        Yellow26->setObjectName(QString::fromUtf8("Yellow26"));
        Yellow26->setGeometry(QRect(1400, 590, 146, 146));
        Yellow26->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red36 = new QLabel(centralwidget);
        Red36->setObjectName(QString::fromUtf8("Red36"));
        Red36->setGeometry(QRect(1400, 750, 146, 146));
        Red36->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow36 = new QLabel(centralwidget);
        Yellow36->setObjectName(QString::fromUtf8("Yellow36"));
        Yellow36->setGeometry(QRect(1400, 750, 146, 146));
        Yellow36->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red46 = new QLabel(centralwidget);
        Red46->setObjectName(QString::fromUtf8("Red46"));
        Red46->setGeometry(QRect(1400, 900, 146, 146));
        Red46->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow46 = new QLabel(centralwidget);
        Yellow46->setObjectName(QString::fromUtf8("Yellow46"));
        Yellow46->setGeometry(QRect(1400, 900, 146, 146));
        Yellow46->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Red56 = new QLabel(centralwidget);
        Red56->setObjectName(QString::fromUtf8("Red56"));
        Red56->setGeometry(QRect(1400, 1050, 146, 146));
        Red56->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Red Chip.png")));
        Yellow56 = new QLabel(centralwidget);
        Yellow56->setObjectName(QString::fromUtf8("Yellow56"));
        Yellow56->setGeometry(QRect(1400, 1050, 146, 146));
        Yellow56->setPixmap(QPixmap(QString::fromUtf8("../build-Connect_Four-Desktop_x86_windows_msvc2019_pe_64bit-Debug/Pictures/Yellow Chip.png")));
        Drop0 = new QPushButton(centralwidget);
        Drop0->setObjectName(QString::fromUtf8("Drop0"));
        Drop0->setGeometry(QRect(410, 110, 161, 171));
        Drop0->setFont(font1);
        Drop1 = new QPushButton(centralwidget);
        Drop1->setObjectName(QString::fromUtf8("Drop1"));
        Drop1->setGeometry(QRect(570, 110, 161, 171));
        Drop1->setFont(font1);
        Drop2 = new QPushButton(centralwidget);
        Drop2->setObjectName(QString::fromUtf8("Drop2"));
        Drop2->setGeometry(QRect(730, 110, 171, 171));
        Drop2->setFont(font1);
        Drop3 = new QPushButton(centralwidget);
        Drop3->setObjectName(QString::fromUtf8("Drop3"));
        Drop3->setGeometry(QRect(900, 110, 161, 171));
        Drop3->setFont(font1);
        Drop4 = new QPushButton(centralwidget);
        Drop4->setObjectName(QString::fromUtf8("Drop4"));
        Drop4->setGeometry(QRect(1060, 110, 161, 171));
        Drop4->setFont(font1);
        Drop5 = new QPushButton(centralwidget);
        Drop5->setObjectName(QString::fromUtf8("Drop5"));
        Drop5->setGeometry(QRect(1220, 110, 171, 171));
        Drop5->setFont(font1);
        Drop6 = new QPushButton(centralwidget);
        Drop6->setObjectName(QString::fromUtf8("Drop6"));
        Drop6->setGeometry(QRect(1390, 110, 151, 171));
        Drop6->setFont(font1);
        Loading = new QLabel(centralwidget);
        Loading->setObjectName(QString::fromUtf8("Loading"));
        Loading->setGeometry(QRect(1646, 1064, 321, 121));
        Loading->setFont(font1);
        PlayAgain = new QPushButton(centralwidget);
        PlayAgain->setObjectName(QString::fromUtf8("PlayAgain"));
        PlayAgain->setGeometry(QRect(1580, 350, 361, 251));
        PlayAgain->setFont(font);
        Exit = new QPushButton(centralwidget);
        Exit->setObjectName(QString::fromUtf8("Exit"));
        Exit->setGeometry(QRect(1580, 660, 361, 241));
        Exit->setFont(font1);
        RedWins = new QLabel(centralwidget);
        RedWins->setObjectName(QString::fromUtf8("RedWins"));
        RedWins->setGeometry(QRect(36, 360, 371, 511));
        QFont font4;
        font4.setPointSize(40);
        font4.setBold(true);
        font4.setWeight(75);
        RedWins->setFont(font4);
        YellowWins = new QLabel(centralwidget);
        YellowWins->setObjectName(QString::fromUtf8("YellowWins"));
        YellowWins->setGeometry(QRect(40, 360, 371, 511));
        YellowWins->setFont(font4);
        ItsATie = new QLabel(centralwidget);
        ItsATie->setObjectName(QString::fromUtf8("ItsATie"));
        ItsATie->setGeometry(QRect(40, 360, 371, 511));
        ItsATie->setFont(font4);
        RedgoesFirst = new QLabel(centralwidget);
        RedgoesFirst->setObjectName(QString::fromUtf8("RedgoesFirst"));
        RedgoesFirst->setGeometry(QRect(1116, 150, 591, 151));
        RedgoesFirst->setFont(font3);
        MainWindow->setCentralWidget(centralwidget);
        Title->raise();
        SaveFile1->raise();
        LoadSaveFile1->raise();
        NewSaveFile1->raise();
        DeleteSaveFile1->raise();
        SaveFile2->raise();
        LoadSaveFile2->raise();
        NewSaveFile2->raise();
        DeleteSaveFile2->raise();
        SaveFile3->raise();
        LoadSaveFile3->raise();
        NewSaveFile3->raise();
        DeleteSaveFile3->raise();
        Human->raise();
        Easy->raise();
        Impossible->raise();
        Red->raise();
        Yellow->raise();
        Back->raise();
        CreateFile->raise();
        DifficultyOutput->raise();
        ComputerOutput->raise();
        Board->raise();
        Red00->raise();
        Yellow00->raise();
        Red10->raise();
        Yellow10->raise();
        Red20->raise();
        Yellow20->raise();
        Red30->raise();
        Yellow30->raise();
        Red40->raise();
        Yellow40->raise();
        Red50->raise();
        Yellow50->raise();
        Red01->raise();
        Yellow01->raise();
        Red11->raise();
        Yellow11->raise();
        Red21->raise();
        Yellow21->raise();
        Red31->raise();
        Yellow31->raise();
        Red41->raise();
        Yellow41->raise();
        Red51->raise();
        Yellow51->raise();
        Red02->raise();
        Yellow02->raise();
        Red12->raise();
        Yellow12->raise();
        Red22->raise();
        Yellow22->raise();
        Red32->raise();
        Yellow32->raise();
        Red42->raise();
        Yellow42->raise();
        Red52->raise();
        Yellow52->raise();
        Red03->raise();
        Yellow03->raise();
        Red13->raise();
        Yellow13->raise();
        Red23->raise();
        Yellow23->raise();
        Red33->raise();
        Yellow33->raise();
        Red43->raise();
        Yellow43->raise();
        Red53->raise();
        Yellow53->raise();
        Red04->raise();
        Yellow04->raise();
        Red14->raise();
        Yellow14->raise();
        Red24->raise();
        Yellow24->raise();
        Red34->raise();
        Yellow34->raise();
        Red44->raise();
        Yellow44->raise();
        Red54->raise();
        Yellow54->raise();
        Red05->raise();
        Yellow05->raise();
        Red15->raise();
        Yellow15->raise();
        Red25->raise();
        Yellow25->raise();
        Red35->raise();
        Yellow35->raise();
        Red45->raise();
        Yellow45->raise();
        Red55->raise();
        Yellow55->raise();
        Red06->raise();
        Yellow06->raise();
        Red16->raise();
        Yellow16->raise();
        Red26->raise();
        Yellow26->raise();
        Red36->raise();
        Yellow36->raise();
        Red46->raise();
        Yellow46->raise();
        Red56->raise();
        Yellow56->raise();
        Drop0->raise();
        Drop1->raise();
        Drop2->raise();
        Drop3->raise();
        Drop4->raise();
        Drop5->raise();
        Drop6->raise();
        Loading->raise();
        PlayAgain->raise();
        Exit->raise();
        RedWins->raise();
        YellowWins->raise();
        ItsATie->raise();
        Name->raise();
        FileName->raise();
        ArtificialIntelligence->raise();
        PlayerOutput->raise();
        Difficulty->raise();
        Player->raise();
        Computer->raise();
        RedgoesFirst->raise();
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName(QString::fromUtf8("statusbar"));
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QApplication::translate("MainWindow", "MainWindow", nullptr));
        Title->setText(QApplication::translate("MainWindow", "Connect 4 Ultimate", nullptr));
        SaveFile1->setText(QApplication::translate("MainWindow", "Name: N/A : Player: N/A : Difficuly: N/A : Computer: N/A\n"
"Red: N/A : Yellow: N/A : Ties: N/A", nullptr));
        LoadSaveFile1->setText(QApplication::translate("MainWindow", "Load", nullptr));
        NewSaveFile1->setText(QApplication::translate("MainWindow", "New", nullptr));
        DeleteSaveFile1->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        SaveFile2->setText(QApplication::translate("MainWindow", "Name: N/A : Player: N/A : Difficuly: N/A : Computer: N/A\n"
"Red: N/A : Yellow: N/A : Ties: N/A", nullptr));
        LoadSaveFile2->setText(QApplication::translate("MainWindow", "Load", nullptr));
        NewSaveFile2->setText(QApplication::translate("MainWindow", "New", nullptr));
        DeleteSaveFile2->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        SaveFile3->setText(QApplication::translate("MainWindow", "Name: N/A : Player: N/A : Difficuly: N/A : Computer: N/A\n"
"Red: N/A : Yellow: N/A : Ties: N/A", nullptr));
        LoadSaveFile3->setText(QApplication::translate("MainWindow", "Load", nullptr));
        NewSaveFile3->setText(QApplication::translate("MainWindow", "New", nullptr));
        DeleteSaveFile3->setText(QApplication::translate("MainWindow", "Delete", nullptr));
        FileName->setPlaceholderText(QApplication::translate("MainWindow", "SaveFile#", nullptr));
        Name->setText(QApplication::translate("MainWindow", "Name:\n"
"(No spaces\n"
"or '\\')", nullptr));
        Player->setText(QApplication::translate("MainWindow", "Player:", nullptr));
        Human->setText(QApplication::translate("MainWindow", "Human", nullptr));
        ArtificialIntelligence->setText(QApplication::translate("MainWindow", "Artificial \n"
"Intelligence", nullptr));
        Difficulty->setText(QApplication::translate("MainWindow", "Difficulty:", nullptr));
        Easy->setText(QApplication::translate("MainWindow", "Easy", nullptr));
        Impossible->setText(QApplication::translate("MainWindow", "Impossible", nullptr));
        Computer->setText(QApplication::translate("MainWindow", "Computer:", nullptr));
        Red->setText(QApplication::translate("MainWindow", "Red", nullptr));
        Yellow->setText(QApplication::translate("MainWindow", "Yellow", nullptr));
        Back->setText(QApplication::translate("MainWindow", "Back", nullptr));
        CreateFile->setText(QApplication::translate("MainWindow", "Create File", nullptr));
        PlayerOutput->setText(QApplication::translate("MainWindow", "N/A", nullptr));
        DifficultyOutput->setText(QApplication::translate("MainWindow", "N/A", nullptr));
        ComputerOutput->setText(QApplication::translate("MainWindow", "N/A", nullptr));
        Board->setText(QString());
        Red00->setText(QString());
        Yellow00->setText(QString());
        Red10->setText(QString());
        Yellow10->setText(QString());
        Red20->setText(QString());
        Yellow20->setText(QString());
        Red30->setText(QString());
        Yellow30->setText(QString());
        Red40->setText(QString());
        Yellow40->setText(QString());
        Red50->setText(QString());
        Yellow50->setText(QString());
        Red01->setText(QString());
        Yellow01->setText(QString());
        Red11->setText(QString());
        Yellow11->setText(QString());
        Red21->setText(QString());
        Yellow21->setText(QString());
        Red31->setText(QString());
        Yellow31->setText(QString());
        Red41->setText(QString());
        Yellow41->setText(QString());
        Red51->setText(QString());
        Yellow51->setText(QString());
        Red02->setText(QString());
        Yellow02->setText(QString());
        Red12->setText(QString());
        Yellow12->setText(QString());
        Red22->setText(QString());
        Yellow22->setText(QString());
        Red32->setText(QString());
        Yellow32->setText(QString());
        Red42->setText(QString());
        Yellow42->setText(QString());
        Red52->setText(QString());
        Yellow52->setText(QString());
        Red03->setText(QString());
        Yellow03->setText(QString());
        Red13->setText(QString());
        Yellow13->setText(QString());
        Red23->setText(QString());
        Yellow23->setText(QString());
        Red33->setText(QString());
        Yellow33->setText(QString());
        Red43->setText(QString());
        Yellow43->setText(QString());
        Red53->setText(QString());
        Yellow53->setText(QString());
        Red04->setText(QString());
        Yellow04->setText(QString());
        Red14->setText(QString());
        Yellow14->setText(QString());
        Red24->setText(QString());
        Yellow24->setText(QString());
        Red34->setText(QString());
        Yellow34->setText(QString());
        Red44->setText(QString());
        Yellow44->setText(QString());
        Red54->setText(QString());
        Yellow54->setText(QString());
        Red05->setText(QString());
        Yellow05->setText(QString());
        Red15->setText(QString());
        Yellow15->setText(QString());
        Red25->setText(QString());
        Yellow25->setText(QString());
        Red35->setText(QString());
        Yellow35->setText(QString());
        Red45->setText(QString());
        Yellow45->setText(QString());
        Red55->setText(QString());
        Yellow55->setText(QString());
        Red06->setText(QString());
        Yellow06->setText(QString());
        Red16->setText(QString());
        Yellow16->setText(QString());
        Red26->setText(QString());
        Yellow26->setText(QString());
        Red36->setText(QString());
        Yellow36->setText(QString());
        Red46->setText(QString());
        Yellow46->setText(QString());
        Red56->setText(QString());
        Yellow56->setText(QString());
        Drop0->setText(QApplication::translate("MainWindow", "Drop\n"
"Here!", nullptr));
        Drop1->setText(QApplication::translate("MainWindow", "Drop\n"
"Here!", nullptr));
        Drop2->setText(QApplication::translate("MainWindow", "Drop\n"
"Here!", nullptr));
        Drop3->setText(QApplication::translate("MainWindow", "Drop\n"
"Here!", nullptr));
        Drop4->setText(QApplication::translate("MainWindow", "Drop\n"
"Here!", nullptr));
        Drop5->setText(QApplication::translate("MainWindow", "Drop\n"
"Here!", nullptr));
        Drop6->setText(QApplication::translate("MainWindow", "Drop\n"
"Here!", nullptr));
        Loading->setText(QApplication::translate("MainWindow", "Loading...", nullptr));
        PlayAgain->setText(QApplication::translate("MainWindow", "Play\n"
"Again!", nullptr));
        Exit->setText(QApplication::translate("MainWindow", "Exit", nullptr));
        RedWins->setText(QApplication::translate("MainWindow", "Red\n"
"Wins!", nullptr));
        YellowWins->setText(QApplication::translate("MainWindow", "Yellow\n"
"Wins!", nullptr));
        ItsATie->setText(QApplication::translate("MainWindow", "It's a\n"
"Tie!", nullptr));
        RedgoesFirst->setText(QApplication::translate("MainWindow", "Red goes First!", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
